### ISSUE TITLE
Macbook Pro M1 - Monterey 12.4 - no tests showing

### ISSUE THREAD

**Issue by antonio-mikulic** [lucono/karma-test-explorer#37] opened 2022-07-25 13:28 UTC
**Describe the Bug**

After performing a clean installation of Visual Studio Code on macOS, with only limited extensions, no tests appear when opening any project. When doing the same thing on a Windows machine it works without an issue. 
When trying to use other addons for Test Explorer UI, such as Python addon, it is loaded properly

**Steps to Reproduce the Behavior**

1. Create a new project, 'ng create test-units'
2. Install Karma Test Explorer and Test Explorer UI
3. Add any unit test
4. Open Test Explorer UI tab
5. No plugin loaded/no tests shown

**Describe the Expected Behavior**

I expected to see all of the tests.

**Provide Debug Logs**
[2022-07-25 13:22:43.598] [DEBUG] [ProjectFactory]: Inspecting workspace folder for testing: /Users/antoniomikulic/Documents/Test projects/test-units
[2022-07-25 13:22:43.598] [DEBUG] [ProjectFactory]: Including projects in workspace folder '/Users/antoniomikulic/Documents/Test projects/test-units' - 'karmaTestExplorer.enableExtension' is set to true
[2022-07-25 13:22:43.598] [DEBUG] [ProjectFactory]: Including projects in workspace folder - One or more inclusion conditions were satisfied: /Users/antoniomikulic/Documents/Test projects/test-units
[2022-07-25 13:22:43.598] [DEBUG] [ProjectFactory]: Angular projects found for workspace folder /Users/antoniomikulic/Documents/Test projects/test-units: ["test-units"]
[2022-07-25 13:22:43.598] [INFO] [ProjectFactory]: Using angular project type for workspace folder '/Users/antoniomikulic/Documents/Test projects/test-units' (auto-detected)
[2022-07-25 13:22:43.598] [DEBUG] [ConfigChangeManager]: Creating config change subscription
[2022-07-25 13:22:43.598] [DEBUG] [Main]: Subscribing for workspace config changes

- Please also capture and attach the logs from the `Karma Server` Output channel when the issue occurs.

**Screenshots**
<img width="1512" alt="Screenshot 2022-07-25 at 15 23 47" src="https://user-images.githubusercontent.com/25779038/180787848-ae7e9859-7377-4f07-88e9-ffd2be27db91.png">

**Please Provide the Following Information**
 
 - OS: macOs Monterey 12.4
 - Environment:  just visual studio code and zsh. VS Code is set up and not in quarantine/read-only
 - Node Version: v18.6.0
 - VS Code Version: 1.69.2, was on the older one but tried a complete reinstall
 - Karma Version: 6.3.0
 - Frameworks: Angular

**Additional Context**

Doing the same on Windows machine works. I tried this for couple repos, where project is in root, subfolder, etc, nothing seemed to work.

**Comment by lucono** [comment] 2022-07-26 02:53
Your detailed report is helpful. Can you also:
- Attach the full debug logs from the other `Karma Test Explorer (...)` and `Karma Server (...)` channels in the VS Code `Output` panel? 
- Try it on an Intel Macbook variant to see if you experience the same issue

**Comment by antonio-mikulic** [comment] 2022-07-26 06:44
Maybe I'm missing something, but I cannot see the Karma Server (...) output channel using VS Code. 

This is using when I select VS Code -> Output -> Karma Test Explorer (workspace), its the only one I see that mentions Karma

[2022-07-26 06:35:13.905] [DEBUG] [ProjectFactory]: Inspecting workspace folder for testing: /Users/antoniomikulic/Documents/Test projects/test-units
[2022-07-26 06:35:13.905] [DEBUG] [ProjectFactory]: Including projects in workspace folder '/Users/antoniomikulic/Documents/Test projects/test-units' - 'karmaTestExplorer.enableExtension' is set to true
[2022-07-26 06:35:13.905] [DEBUG] [ProjectFactory]: Including projects in workspace folder - One or more inclusion conditions were satisfied: /Users/antoniomikulic/Documents/Test projects/test-units
[2022-07-26 06:35:13.905] [DEBUG] [ProjectFactory]: Angular projects found for workspace folder /Users/antoniomikulic/Documents/Test projects/test-units: ["just-todo-it"]
[2022-07-26 06:35:13.905] [INFO] [ProjectFactory]: Using angular project type for workspace folder '/Users/antoniomikulic/Documents/Test projects/test-units' (auto-detected)
[2022-07-26 06:35:13.905] [DEBUG] [ConfigChangeManager]: Creating config change subscription
[2022-07-26 06:35:13.905] [DEBUG] [Main]: Subscribing for workspace config changes
[2022-07-26 06:39:15.233] [INFO] [ConfigChangeManager]: Configuration changed

 
I will check if someone has Intel MacBook for testing

**Comment by BlairLeduc** [comment] 2022-07-26 09:22
I am experiencing the same in the same environment. Unfortunately, I cannot add anything more, the logs are also the same.

**Comment by BlairLeduc** [comment] 2022-07-26 09:40
Additional frobbing found that if I add "src" as a project, it will start the Karma server, but the server complains that it cannot find the karma.conf.js file.

    Error: Cannot find module '<path>/src/karma.conf.js'

If I specify "../karma.conf.js" as the path for the config file, then the server complains that:

    Server start failed on port 9976: Error: The '@angular-devkit/build-angular/plugins/karma' karma plugin is meant to be used from within Angular CLI and will not work correctly outside of it.

Also, this occurs on both macOS and using WSL on Windows. So it appears not to be an Apple Silicon-based problem.

I also do have a "test" target with a "karmaConfig" in my angular.json file.

**Comment by lucono** [comment] 2022-07-27 05:15
I'm able to reproduce this, which seems to be an issue for new Angular projects for which the `angular.json` config does not specify a `defaultProject` - which [has been deprecated](https://github.com/angular/angular-cli/issues/23470). Karma Test Explorer also [deprecated](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#changed) its `defaultAngularProjects` extension setting in `v0.7.0`.

I've made a fix in the `beta` branch - [download](https://github.com/lucono/karma-test-explorer/suites/7537387612/artifacts/310724175) the `.vsix` from the CI build or build it yourself directly from the branch, and test to confirm if it resolves the issue for you.

**Comment by antonio-mikulic** [comment] 2022-07-27 14:28
Hey, that did manage to fix it for me! Thank you for the help!

<img width="1512" alt="Screenshot 2022-07-27 at 16 25 29" src="https://user-images.githubusercontent.com/25779038/181272511-06e4edf5-eaf8-4861-a13d-b9c7be1bc6f9.png">

**Comment by lucono** [comment] 2022-07-28 02:12
Great, released in [v0.7.2](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#072---jul-27-2022).

Don't hesitate to open a new issue if you experience any other problems.

**Closed as completed by lucono** 2022-07-28 02:12 UTC
Labels: bug

**Comment by BlairLeduc** [comment] 2022-07-28 08:06
Yes, v0.7.2 works for me as well! Thank you!
