### ISSUE TITLE
Cannot debug, if the project name contains a namespace at package.json

### ISSUE THREAD

**Issue by ViktorLajos** [lucono/karma-test-explorer#33] opened 2022-07-06 16:28 UTC
I encountered an issue when my package.json looked like this:

```
{
	"name": "@company/canvas-helper",
	"author": "...",
	"version": "1.0.3",
	"main": "lib/index.js",
	"types": "lib/index.d.ts",
	"scripts": {
		"build": "tsc --project tsconfig.prod.json",
		"test": "karma start karma.config.js"
	},
	"devDependencies": {
		"@types/jasmine": "^4.0.3",
		"coverage-istanbul-loader": "^3.0.5",
		"istanbul-instrumenter-loader": "^2.0.0",
		"karma": "^6.4.0",
		"karma-chrome-launcher": "^3.1.1",
		"karma-coverage-istanbul-reporter": "^3.0.3",
		"karma-jasmine": "^5.1.0",
		"karma-junit-reporter": "^2.0.1",
		"karma-sourcemap-loader": "^0.3.8",
		"karma-webpack": "^5.0.0",
		"ts-loader": "^9.2.6",
		"ts-node": "^10.4.0",
		"typescript": "^4.5.5",
		"webpack": "^5.68.0"
	},
	"files": [
		"lib/**/*",
		"types/**/*"
	]
}
```
It will not attach the debugger. The output console looks like this:
```
[2022-07-06 17:05:42.970] [INFO] [Adapter]: Debug test run started
[2022-07-06 17:05:43.738] [INFO] [Adapter]:  Debug test run finished in 0.77 secs
[2022-07-06 17:05:44.336] [INFO] [Debugger]: Debug session 'Karma Test Explorer Debugging' has ended
```

 But if I change the name to just **canvas-helper** it starts working

**Expected Behavior:**

I would like to use npm namespaces for the package name, and being able to debug the tests

**Comment by lucono** [comment] 2022-07-07 02:24
I'm not able to reproduce the failure by adding a namespace to the package name of a working project.

Can you attach debug logs (ie. with `karmaTestExplorer.logLevel` set to `debug`). Be sure to include the effective config settings which are printed near the start of the logs, including the `debuggerConfig` and `defaultDebugPort` settings.

Also provide environment information, including OS, Environment (e.g. Dev Container), Node Version, VSCode Version, Karma Version, Frameworks (e.g. Angular, Jasmine, Mocha).

**Comment by ViktorLajos** [comment] 2022-07-07 08:15
> I'm not able to reproduce the failure by adding a namespace to the package name of a working project.
> 
> Can you attach debug logs (ie. with `karmaTestExplorer.logLevel` set to `debug`). Be sure to include the effective config settings which are printed near the start of the logs, including the `debuggerConfig` and `defaultDebugPort` settings.
> 
> Also provide environment information, including OS, Environment (e.g. Dev Container), Node Version, VSCode Version, Karma Version, Frameworks (e.g. Angular, Jasmine, Mocha).

Thank you for your quick response, I'll do a Minimal Reproduction Case repo, and add the missing information later today

**Comment by ViktorLajos** [comment] 2022-07-08 05:55
> I'm not able to reproduce the failure by adding a namespace to the package name of a working project.
> 
> Can you attach debug logs (ie. with `karmaTestExplorer.logLevel` set to `debug`). Be sure to include the effective config settings which are printed near the start of the logs, including the `debuggerConfig` and `defaultDebugPort` settings.
> 
> Also provide environment information, including OS, Environment (e.g. Dev Container), Node Version, VSCode Version, Karma Version, Frameworks (e.g. Angular, Jasmine, Mocha).

Thank you for your quick response, I made a minimal reproduction case, you can find the repo here: [https://github.com/ViktorLajos/karma-test-explorer-bug](https://github.com/ViktorLajos/karma-test-explorer-bug)

If I put a breakpoint at the Counter.test.ts line 5, it is not stopping, but if I remove the @company/ part from the package.json name field and reload the vscode, then it works perfectly. Same issue if I add the `"testExplorer.useNativeTesting": true` settings to the settings.json

Debug output log: [debug.log](https://gist.github.com/ViktorLajos/8c529500d05215938a81dcd36d036d58)

**Os**: `Windows 10 Home`
**Node**: `v14.17.1`
**VsCode**:
```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
```

**Comment by lucono** [comment] 2022-07-09 23:11
Thanks for the additional info @ViktorLajos.

Using the test project, I'm able to hit breakpoints and debug tests normally, while having the namespace in the package name and `testExplorer.useNativeTesting` set to `true`. See screenshot below.

![image](https://user-images.githubusercontent.com/8845985/178125266-74241618-72b7-46a9-8475-0997e08d97b7.png)

**Comment by lucono** [comment] 2022-07-28 02:21
@ViktorLajos - Is this still an issue with the latest ([v0.7.2](https://github.com/lucono/karma-test-explorer/blob/master/CHANGELOG.md#072---jul-27-2022)) version?

**Comment by lucono** [comment] 2022-08-16 04:22
Closing, as not able to reproduce.

**Closed as completed by lucono** 2022-08-16 04:22 UTC
Labels: bug
